---
name: Convert-Color-Library
version: 0.02
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
abstract: 'named lookup of colors from C<Color::Library>'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Color::Library: 0
  Convert::Color: 0.02
build_requires:
  Test::More: 0
provides:
  Convert::Color::Library:
    file: lib/Convert/Color/Library.pm
    version: 0.02
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
